--@"경로\member.sql";
--@"경로\product.sql";
--@"경로\seller.sql";
--@"경로\order.sql";
--@"경로\basket.sql";
--@"경로\qna.sql";
--@"경로\reveiw.sql";
--@"경로\seller.sql";
--commit;

@"D:\project\second\secProjectDB\member.sql";
@"D:\project\second\secProjectDB\product.sql";
@"D:\project\second\secProjectDB\seller.sql";
@"D:\project\second\secProjectDB\order.sql";
@"D:\project\second\secProjectDB\basket.sql";
@"D:\project\second\secProjectDB\qna.sql";
@"D:\project\second\secProjectDB\reveiw.sql";
@"D:\project\second\secProjectDB\seller.sql";
commit;